### ISSUE TITLE
Crash when click on save

### ISSUE THREAD

**Issue by shuvashish76** [AlexanderTreml/AST-Tuner#1]
Crash logs:

```
FATAL EXCEPTION: DefaultDispatcher-worker-5
Process: com.alexander_treml.asttuner, PID: 20649
java.lang.IllegalStateException: Not implemented
	at androidx.work.CoroutineWorker.getForegroundInfo$suspendImpl(CoroutineWorker.kt:100)
	at androidx.work.CoroutineWorker.getForegroundInfo(Unknown Source:0)
	at androidx.work.CoroutineWorker$getForegroundInfoAsync$1.invokeSuspend(CoroutineWorker.kt:134)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2aa6ec8, Dispatchers.Default]
```

**Comment by AlexanderTreml** [comment]
Thank you for reporting this. Turns out this is an issue when using `setExpedited()` on workers under Android 11 and below. 

In this case the worker would need to override `getForegroundInfo()` (see https://stackoverflow.com/questions/67749284/how-does-setexpedited-work-and-is-it-as-goodreliable-as-a-foreground-service/68468786#68468786)

Since that would require the permission to send notifications, I opted to just not use `setExpedited()` instead. That wasn't really necessary in the first place, I just didn't think it would cause issues.

I redid the latest release and it should be fixed now!
